# Generated by Django 5.2.5 on 2025-10-09 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='nome', max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('instituicao_ensino', models.CharField(blank=True, help_text='Obrigatório para alunos e professores', max_length=100, null=True)),
                ('perfil', models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('ORGANIZADOR', 'Organizador')], max_length=15)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('SEMINARIO', 'Seminário'), ('PALESTRA', 'Palestra'), ('MINICURSO', 'Minicurso'), ('SEMANA_ACADEMICA', 'Semana Acadêmica'), ('OUTRO', 'Outro')], max_length=20)),
                ('nome', models.CharField(db_column='nome', max_length=200)),
                ('data_inicial', models.DateTimeField()),
                ('data_final', models.DateTimeField()),
                ('horario', models.TimeField()),
                ('local', models.CharField(max_length=100)),
                ('palestrante_nome', models.CharField(blank=True, help_text='Nome do Palestrante ou Convidado', max_length=150, null=True)),
                ('quantidade_participantes', models.PositiveIntegerField(help_text='Limite de inscrições para o evento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('organizador_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_organizados', to='aulaweb.usuario')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'evento',
                'ordering': ['data_inicial', 'horario'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('certificado_emitido', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='aulaweb.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='aulaweb.usuario')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'db_table': 'inscricao',
                'ordering': ['-data_inscricao'],
                'unique_together': {('usuario', 'evento')},
            },
        ),
    ]
